[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
all-features = true

[advisories]
unmaintained = "workspace"
unsound = "all"
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]

[[licenses.exceptions]]
name = "runfossil-cli"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-core"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-container"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-fs"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-net"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-pack"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-plan"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-proc"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-service"
allow = ["MIT"]

[[licenses.exceptions]]
name = "runfossil-store"
allow = ["MIT"]

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
