[package]
name = "runfossil-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
runfossil-core = { path = "../runfossil-core" }
runfossil-store = { path = "../runfossil-store" }
runfossil-fs = { path = "../runfossil-fs" }
socket2 = "0.5"

[lints]
workspace = true
