[package]
name = "runfossil-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
runfossil-core = { path = "../runfossil-core" }
runfossil-fs = { path = "../runfossil-fs" }
runfossil-store = { path = "../runfossil-store" }

[lints]
workspace = true
