[package]
name = "runfossil-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
runfossil-core = { path = "../runfossil-core" }

[dev-dependencies]
criterion = { version = "0.8", default-features = false }
tempfile = "3"

[[bench]]
name = "store_bench"
harness = false

[lints]
workspace = true
